services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: shilov
      POSTGRES_PASSWORD: zzz
      POSTGRES_DB: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - 5444:5432
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9090:8080
    environment:
      KC_HOSTNAME: http://localhost:9090
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: shilov
      KC_DB_PASSWORD: zzz
      KEYCLOAK_ADMIN: shilov
      KEYCLOAK_ADMIN_PASSWORD: zzz
    networks:
      - keycloak-network
    depends_on:
      - postgres
    command:
      - "start-dev"

  pet-auth:
    container_name: pet-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - keycloak
    networks:
      - keycloak-network
    restart: unless-stopped

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_keycloak_data:
    name: pet-auth_postgres_keycloak_data
    driver: local