services:
  postgres:
    container_name: Postgres
    image: postgres:15
    environment:
      POSTGRES_USER: SHILOV
      POSTGRES_PASSWORD: zzz
      POSTGRES_DB: keycloak
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    ports:
      - 5444:5432
    networks:
      - keycloak-network
    restart: unless-stopped

  keycloak:
    container_name: Keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 9090:8080
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: SHILOV
      DB_PASSWORD: zzz
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-network
    depends_on:
      - postgres
    command:
      - "start-dev"

  pet-auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - keycloak
    restart: unless-stopped

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_keycloak_data:
    driver: local